version: "3.9"
services:
  chatgpt-next-web-earlybird:
    profiles: [ "no-proxy" ]
    container_name: chatgpt-next-web-earlybird
    image: dogtititi/chatgpt-next-web-earlybird
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
      - HOSTNAME=0.0.0.0
      - PORT=3000

  chatgpt-next-web-earlybird-proxy:
    profiles: [ "proxy" ]
    container_name: chatgpt-next-web-earlybird-proxy
    image: dogtititi/chatgpt-next-web-earlybird
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - PROXY_URL=$PROXY_URL
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
      - HOSTNAME=0.0.0.0
      - PORT=3000
